---
title: "Extract Telecom Data from MySQL"
author: "Lowson Li and Peter Lai"
output:
  html_notebook:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: simplex
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# User variables

## Load library

```{r}
library(tidyverse)
library(readr)
library(data.table)
library(rio)
```

## Import user variable data

```{r}
# inspect the number of files generated by mysql
n_files_var <- list.files(
  path = "/var/lib/mysql-files/",
  pattern = ".*var.csv",
  full.names = TRUE
) %>% length()

n_files_var
```

```{r}
# import all the files in the list 
tbl_fread_var <-
  list.files(
    path = "/var/lib/mysql-files/",
    pattern = ".*var.csv",
    full.names = TRUE
  ) %>%
  map_df(~ fread(., header = FALSE, verbose = FALSE))
```

```{r}
# add column names
colnames(tbl_fread_var) <- c(
  "SERV_ID", "MSISDN", "MONTH_NO", "CERT_NBR", "EMPLOY_FLAG",
  "STUDENT_FLAG", "RURAL_FLAG", "ROG", "ECCEN", "ENT", "FREQ_CENTER",
  "CENTER", "MODEL", "BRAND", "SMART", "LEVEL", "PRICE", "CONTRACT",
  "GENDER"
)
```

```{r}
# users by month
tbl_fread_var %>% 
  group_by(MONTH_NO) %>% 
  summarise(count = n_distinct(SERV_ID,MSISDN))
```

## Mutate data

### Balanced Panel

```{r echo=TRUE}
# get user-device pair that appears in all month
user_in_all_month <-
  tbl_fread_var %>%
  group_by(SERV_ID, MSISDN) %>%
  count() %>%
  filter(n == 11)

user_var <-
  tbl_fread_var %>%
  semi_join(user_in_all_month, by = c("SERV_ID","MSISDN"))
```

```{r echo=TRUE}
# trim redundant space
# mysql use "\N" as NA, replace "\N" with NA
# some columns have empty sting, replace with NA
user_var <-
  user_var %>%
  mutate(across(.cols = everything(), .fns = ~ str_trim(., side = "both"))) %>%
  mutate(across(.cols = everything(), .fns = ~ na_if(., "\\N"))) %>%
  mutate(across(.cols = everything(), .fns = ~ na_if(., "")))
```

### Unbalanced Panel

```{r}
# trim redundant space
# mysql use "\N" as NA, replace "\N" with NA
# some columns have empty sting, replace with NA
user_var_ub <-
  tbl_fread_var %>%
  mutate(across(.cols = everything(), .fns = ~ str_trim(., side = "both"))) %>%
  mutate(across(.cols = everything(), .fns = ~ na_if(., "\\N"))) %>%
  mutate(across(.cols = everything(), .fns = ~ na_if(., "")))
```

## Check data

### Balanced Panel

```{r}
glimpse(user_var)
```

```{r}
user_var %>% head(20)
```

```{r}
user_var %>%
  group_by(MONTH_NO) %>%
  summarise(count = n())
```

```{r}
# number of row
nrow(user_var)
```

### Unbalanced Panel

```{r}
glimpse(user_var_ub)
```

```{r}
user_var_ub %>% head(20)
```

```{r}
user_var_ub %>%
  group_by(MONTH_NO) %>%
  summarise(count = n())
```

```{r}
# number of row
nrow(user_var_ub)
```

## Export data

```{r}
# export unbalanced panel
rio::export(user_var,"../Output/user_var_b.csv")
# export balanced panel
rio::export(user_var_ub,"../Output/user_var_ub.csv")
```

# User links

## Import user link data

```{r}
# inspect the number of files generated by mysql
n_files_link <- list.files(
  path = "/var/lib/mysql-files/",
  pattern = ".*link.csv",
  full.names = TRUE
) %>% length()

n_files_link
```

```{r message=FALSE}
# import all the files in the list 
tbl_fread_link <-
  list.files(
    path = "/var/lib/mysql-files/",
    pattern = ".*link.csv",
    full.names = TRUE
  ) %>%
  map_df(~ bind_cols(fread(., header = FALSE, verbose = FALSE), str_extract(., "\\d{6}")))
```

## Mutate data

```{r}
# add column names
colnames(tbl_fread_link) <- c("FROM", "TO", "MONTH_NO")
```

```{r}
# leave connection for users appears in all month
user_link <-
  tbl_fread_link %>%
  semi_join(user_in_all_month, by = c("FROM" = "MSISDN"))
```

## Check data

### Caller from Balanced Panel

```{r}
user_link %>% head(20)
```

```{r}
# check connections by month
user_link %>%
  group_by(MONTH_NO) %>%
  summarise(count = n())
```

```{r}
# number of row
nrow(user_link)
```

### Caller from Unbalanced Panel

```{r}
tbl_fread_link %>% head(20)
```

```{r}
# check connections by month
tbl_fread_link %>%
  group_by(MONTH_NO) %>%
  summarise(count = n())
```

```{r}
# number of row
nrow(user_link)
```

## Export data

```{r}
# export balanced panel
rio::export(user_link,"../Output/user_link_b.csv")
# export unbalanced panel
rio::export(tbl_fread_link,"../Output/user_link_ub.csv")
```
